[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity1"

[network]
port = 30301

[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["http://localhost:8000"]

[ui]
port = 8181

[websockets]
port = 8547

[account]
password = ["node.pwds"]

[mining]
engine_signer = "0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2"
reseal_on_txs = "all"
force_sealing = true

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"